name: Go

env:
  GIN_MODE: release
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    defaults:
      run:
        working-directory: ./8_go_ci
    steps: 
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with: 
        go-version-file: './8_go_ci/go.mod'
        cache: true

    - name: Revive Action
      uses: morphy2k/revive-action@v2

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1
      with:
        working-directory: './8_go_ci'

    - name: Build
      run: |
        go mod download
        go install gotest.tools/gotestsum@latest

    - name: Test
      run: |
        gotestsum --format=standard-verbose --junitfile=junit.xml

    - name: Publish test report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure()
      with:
        report_path: '**/junit.xml'
        detailed_summary: true
        include_passed: true